eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: client
          uri: lb://CLIENT
          predicates:
            - Path=/service/**